baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: FRIENDSHIP
    # Hero subtitle (optional)
    subtitle: Mang Cả Thế Giới Đến Mái Ấm Của Bạn!
    # Button text
    buttontext: GỬI YÊU CẦU NGAY BÂY GIỜ
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /
  - title: Pricing
    url: /
  - title: Dropdown
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: Log in
    url: /
  - title: Sign up
    url: /
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: NHỮNG ĐIỀU TUYỆT VỜI
    subtitle: FRIENDSHIP MANG ĐẾN CHO BẠN
    tiles:
    - title: GIAO HÀNG 
      icon: mouse-globe
      text: TẬN CỬA HOẶC TẠI BÀN
      url: /
      buttonText: Gửi Yêu Cầu Ngay Bây Giờ!
    - title: REVIEW ĐỒ ĂN
      icon: laptop-cloud
      text: KHÁCH QUAN, CHÍNH XÁC
      url: /
      buttonText: Gửi Yêu Cầu Ngay Bây Giờ!
    - title: GIÚP VIỆC
      icon: plug-cloud
      text: CHU ĐÁO, TẬN TỤY
      url: /
      buttonText: Gửi Yêu Cầu Ngay Bây Giờ!
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Super
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Nhận Xét Của Khách Hàng Về Chúng Tôi
    subtitle: -------------------
    clients:
    - name: Lê Nguyễn Hoàng Trâm
      quote: Dịch vụ tạm tạm chấp nhận được, cần cố gắng hơn.
      job: Căn Hộ 702 Tòa Nhà CT4
      img: 1
    - name: Lý Khắc Cường
      quote: Tốc độ giao hàng nhanh nhưng chưa chính xác thời điểm tôi mong muốn.
      job: Căn Hộ 208 Tòa Nhà CT1
      img: 2
    - name: Ngô Nguyễn Hùng Anh
      quote: Nhân viên giao hàng khá thân thiện nhưng hơi cẩu thả.
      job: Căn Hộ 904 Tòa Nhà CT3
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second

deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: mydeployment
      cloudFrontDistributionID: ''
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: false
    - pattern: ^.+\.(html|xml|json)$
      gzip: true

          